rapidsai/gpuci-build-environment

README.md
build-scripts/libgdf-master.sh
build-scripts/libgdf-prb.sh
build-scripts/pygdf-master.sh
build-scripts/pygdf-prb.sh

This allows for dynamic updates to the gpuCI tests run on http://gpuci.gpuopenanalytics.com until the new pipeline and Jenkinsfile methods are available.

Add gpuCI Jenkins Build Scripts to Repo

---

build-scripts/libgdf-master.sh
build-scripts/libgdf-prb.sh

For Jenkins to display the results of the GoogleTests along with the Python tests already found at: http://gpuci.gpuopenanalytics.com/job/libgdf-master/lastCompletedBuild/testReport/python.tests/

Generate XML Reports for GoogleTests for Jenkins CI

---

build-scripts/libgdf-master.sh
build-scripts/libgdf-prb.sh

The conda env in libgdf installs cmake 3.6.3 when 3.12 is installed in the container and needed for building

Remove cmake version in libgdf conda env

---

build-scripts/pygdf-prb.sh

Using --remote with submodules breaks the code by pulling the latest master versions, so we want to use the pinned versions in the repo
Also changed the clones to checkout at the same time and to use the branch name instead

Bug submodules `--remote` causes master versions of submodules to be pulled

---

.condarc-cuda10.0
.condarc-cuda9.2
Dockerfile

The `conda-forge` channel removed its compilers and expects users to rely on the `defaults` channel to get them. This means we need to add `defaults` back to the channels, but at the bottom of the priority list, so it only gets used when the packages don't exist in `conda-forge`. Additionally, pinned the compiler libs to version `7.3.0` which is in line with what was expected from the `conda-forge` channel.

[FIX] Fix package dependency errors

---

.condarc-cuda10.0
.condarc-cuda9.2
Dockerfile

Moves the .condarc to the root conda environment so that it isn't `root` user specific.
Additionally, blacklists v8.2.0 compilers/libs so that they can't bite us in the butt.
Also, creates the gdf environment in one go so that there isn't any packages installed and then downgraded inadvertently.

[REVIEW] Move .condarc to conda root environment, prevent v8.2.0 compilers/libs from being installed, 

---

.condarc-cuda10.0
.condarc-cuda9.2

Thought the blacklist factored into the solver but seems like it doesn't and just errors if it grabs that package. Remove for now.

[REVIEW] Remove blacklisted compiler packages

---

Dockerfile

Since we'll be using this in conjunction with py.test, we should add this to our base Docker images instead of adding the install to the build scripts.

[REVIEW] Add python test coverage package to base Docker image

---

Dockerfile
Dockerfile.centos7

This will be to run them in check only mode as part of the style checker for cudf but will encourage other libraries to use them as well.

Add `black` and `isort` to the gpuci environment

---

.condarc
.condarc-cuda10.0
.condarc-cuda9.2
Dockerfile
Dockerfile.centos7

Since the CUDA version is now controlled by the `cudatoolkit` conda package, the labels should be removed.

[REVIEW] Remove cuda labels from .condarc

---

miniconda-cuda/Dockerfile

Certain RAPIDS tests require the presence of `/etc/timezone` on Ubuntu.
Tested by building the image and verifying the package is present.

Added tzdata to Ubuntu Dockerfile

---

Dockerfile
Dockerfile.centos7

Adding `libclang` from the `rapidsai` conda channel to support the usage of clang-format in cuML (and probably other RAPIDS libraries). Blocks PR https://github.com/rapidsai/cuml/pull/1468

[REVIEW] Add rapidsai libclang to Dockerfile

---

Dockerfile
Dockerfile.centos7

Following up on [this comment]( https://github.com/rapidsai/rmm/pull/198#discussion_r357772519 ) to add CuPy to the gpuCI containers. Starting off with the version of CuPy we used in the RAPIDS 0.11.0 release (namely 6.6.0). Though we may want to bump this to CuPy 7.0.0 in the future.
cc @raydouglass @madsbk @kkraus14 @harrism @mike-wendt

Add CuPy 6.6.0 to the gpuCI containers

---

python3.5/Dockerfile
python3.5/Dockerfile.centos7

There was an ask to create Python 3.5 images. Unfortunately, many of the library versions we use are Python >=3.6.
So I downgraded the dependencies to Python 3.5 compatible versions. The only package that doesn't have a compatible version is `black`.
This also meant a lower conda version which had some implications:
- No conda install in non-base environment
- No conda-build in  non-base environment since it depends on conda
- `conda clean` command has different flags
Note that no changes to `Dockerfile.drivers` are necessary. It just has to be built with `--build-arg PYTHON_VERSION=3.5`.
| Libary  | Python 3.6 | Python 3.5 |
| - | - | - |
| cython  | 0.29 | 0.28 |
| numba | 0.46.0 | 0.38.1 |
| numpy | 1.17.3 | 1.13.3 |
| pandas | 0.24.2 | 0.23.4 |
| pyarrow | 0.15.0 | 0.10.0 |
| …

[REVIEW] Python 3.5 images

---

Dockerfile
Dockerfile.centos7

In the devel container we use openblas 2.14, matching to that spec

FIX Bump openblas to 2.14

---

Dockerfile
Dockerfile.centos7

`rapidsai::libclang` was a package for temporary usage until conda-forge clang and clang-tools packages were properly backported for their version 8 releases. Now that we have these 2 packages available on conda-forge for version 8, it is better for us to use them.
This update is also needed for the following 2 PRs in cuML:
1. https://github.com/rapidsai/cuml/pull/1972
2. https://github.com/rapidsai/cuml/pull/1945

[REVIEW] Use standard clang and clang-tools package instead of libclang

---

Dockerfile

This PR adds `pytest-timeout` to our base Dockerfile so that we can prevent longrunning jobs.

Add pytest-timeout

---

Dockerfile.centos7
python3.5/Dockerfile
python3.5/Dockerfile.centos7

This PR adds `pytest-timeout` to centos. I forgot to add it in #73.

Add pytest-timeout to centos

---

rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

This PR updates the `aws` cli to the latest version in anticipation of the benchmarking efforts.
These changes were tested on `dgx07` and seem to be working fine.

Update awscli to latest

---

ci/gpuci/run.sh

Duplicate of https://github.com/rapidsai/docker/pull/112
---
This PR reverts a commit on Thursday that has been breaking our builds.
The Jenkins agents that run Docker builds do not have `conda` installed and there are no plans to install `conda` at this time. Therefore `gpuci-tools` should be installed via `curl` to prevent builds from breaking.

Revert "FIX Update to use conda install instead of curl"

---

miniconda-cuda-driver/Dockerfile

Use `conda-build` from `conda-forge` to get the latest version needed for package builds in integration and other repos. Version `3.19.2` is needed and not available in the `defaults` channel.

ENH Update conda-build version

---

rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

There are a few mentions of ccache that were leftover from when ccache used to be built in the `gpuci/rapidsai` images. This PR cleans them up as ccache is now being built from source in the `devel` images.

[REVIEW] Remove Leftover Mentions of Ccache

---

rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

This PR installs `jq` directly from source (https://stedolan.github.io/jq/download/) on both rapidsai `devel` images.
These changes were tested and confirmed working locally.
Additionally, it adds a `-q` (quiet) flag to the `unzip` command so it doesn't output so much during Docker builds.

Update jq installation

---

ci/axis/miniconda-cuda-driver.yml
ci/axis/miniconda-cuda.yml
ci/gpuci/run.sh

Add CUDA 11.0 versions for `miniconda-cuda` & `miniconda-cuda-driver` to support building packages needed for bringup.
Also add PR testing back to this repo with script changes to support the new jobs & PR pipeline: https://gpuci.gpuopenanalytics.com/job/gpuci/job/gpuci-build-environment/

ENH Add CUDA 11.0 to miniconda-cuda/-driver & PR testing

---

CONTRIBUTING.md

This PR changes any 'master' references to 'main' in markdown files throughout the repo as part of the new 'master' to 'main' branch migration.

[skip ci] Update master references for main branch

---

ci/axis/miniconda-cuda.yml
ci/gpuci/run.sh
miniconda-cuda/Dockerfile

CUDA 11 images no longer set  which is relied upon for our conda recipes and various other scripts. This explicitly sets  for all  images and should effectively patch all images preventing them from encountering this bug

BUG Fix nvidia/cuda images that do not set CUDA_VERSION

---

ci/gpuci/run.sh

Was incorrectly checking the wrong env var so this was not being passed and resulted in broken images.

FIX Correct check to pass FULL_CUDA_VER build arg

---

CONTRIBUTING.md
legacy/miniconda-cuda-rapidsenv/Dockerfile
legacy/miniconda-cuda-rapidsenv/Dockerfile.centos7
rapidsai/base-runtime.Dockerfile
rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

From updates in conda-forge and changes made in rapidsai/integration#91 we no longer need to rely on installing `nomkl` to ensure that mkl is not installed.
This frees up users and libraries to install `pytorch` and `mkl` as needed.

ENH Remove `nomkl` from `rapids` conda env

---

ci/axis/rapidsai-driver.yml
ci/axis/rapidsai.yml

This enables image builds for RAPDIS v0.16 as burndown started yesterday.

FIX Add 0.16 RAPIDS to nightly axis

---

.condarc
ci/axis/rapidsai.yml
rapidsai/base-runtime.Dockerfile
rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

Add gpuci to channels and remove explicit `-c gpuci` flags.
**Question:**
- should the `--override-channels -c gpuci` also be removed from miniconda-cuda-driver https://github.com/rapidsai/gpuci-build-environment/blob/2b01ee1d442a8339976d0e4f332c58f9c1a6149b/miniconda-cuda-driver/Dockerfile#L14

[REVIEW] Add gpuci to channels

---

rapidsai/base-runtime.Dockerfile

Replaces `conda create` with `gpuci_conda_retry create`
This may be changed later on based on https://github.com/rapidsai/gpuci-tools/issues/6

ENH Change conda to gpuci_conda_retry

---

legacy/miniconda-cuda-rapidsenv/Dockerfile.centos7
rapidsai/base-runtime.Dockerfile
rapidsai/devel-centos7.Dockerfile
rapidsai/devel.Dockerfile

Add `gpuci-tools` to be installed when activating rapids in images. Allows for easy access to tools such as `gpuci logger` functionality.
Has been tested by running `gpuci_logger` in the resultant `gpuci/rapidsai` image after removing `/opt/conda/bin` from the `PATH`.

ENH Add Gpuci-Tools to Rapid Env Activate

---

templates/ci/checks/changelog.sh
templates/ci/cpu/upload_anaconda.sh

This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.

[REVIEW] Update CI scripts to remove references to master [skip ci] 

---

ci/axis/miniconda-cuda.yml

Disable builds from using `gpuci/cuda` that held our archived versions of CUDA 10.2 and 11.0 GA. Instead use the recently updated `nvidia/cuda` images that includes CUDA 11.0 Update 1.
Leaving the exclusions and `gpuci/cuda` options in but commented out so if we need to revert we can quickly.

ENH Use nvidia/cuda for CUDA 10.2 & 11.0 Update 1

---

ci/axis/rapidsai-driver.yml
ci/axis/rapidsai.yml

With 0.15 released we no longer need to build 0.15 images

ENH Disable 0.15 builds in 0.16 branch
